### ISSUE TITLE
CLI weirdness

### ISSUE THREAD

**Issue by abhijitkane** [postmanlabs/postman-collection-transformer#24] opened 2016-07-25 09:34 UTC
$> bin/transform-collection.js
o/p:
```
  Commands:

    convert [options]    Convert Postman Collection from one format to another
    validate [options]   Verify whether a postman collection adheres to version specifications
    *                    Display usage text
    help [cmd]           display help for [cmd]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

$> bin/transform-collection.js help convert
```
  Usage: transform-collection [command] [options]


  Commands:

    convert [options]    Convert Postman Collection from one format to another
    validate [options]   Verify whether a postman collection adheres to version specifications
    *                    Display usage text
    help [cmd]           display help for [cmd]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number


  transform-collection-convert(1) does not exist, try --help
```

$> bin/transform-collection.js --help
```
  Usage: transform-collection [command] [options]


  Commands:

    convert [options]    Convert Postman Collection from one format to another
    validate [options]   Verify whether a postman collection adheres to version specifications
    *                    Display usage text
    help [cmd]           display help for [cmd]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

```

help?

**Comment by czardoz** [comment] 2016-07-25 11:11
Duplicate of #19 
Workaround is mentioned in that issue

**Closed by czardoz** 2016-07-25 11:11 UTC
